
#ifndef VTKTESTINGDATAMODEL_EXPORT_H
#define VTKTESTINGDATAMODEL_EXPORT_H

#ifdef VTKTESTINGDATAMODEL_STATIC_DEFINE
#  define VTKTESTINGDATAMODEL_EXPORT
#  define VTKTESTINGDATAMODEL_NO_EXPORT
#else
#  ifndef VTKTESTINGDATAMODEL_EXPORT
#    ifdef TestingDataModel_EXPORTS
        /* We are building this library */
#      define VTKTESTINGDATAMODEL_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKTESTINGDATAMODEL_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKTESTINGDATAMODEL_NO_EXPORT
#    define VTKTESTINGDATAMODEL_NO_EXPORT 
#  endif
#endif

#ifndef VTKTESTINGDATAMODEL_DEPRECATED
#  define VTKTESTINGDATAMODEL_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKTESTINGDATAMODEL_DEPRECATED_EXPORT
#  define VTKTESTINGDATAMODEL_DEPRECATED_EXPORT VTKTESTINGDATAMODEL_EXPORT VTKTESTINGDATAMODEL_DEPRECATED
#endif

#ifndef VTKTESTINGDATAMODEL_DEPRECATED_NO_EXPORT
#  define VTKTESTINGDATAMODEL_DEPRECATED_NO_EXPORT VTKTESTINGDATAMODEL_NO_EXPORT VTKTESTINGDATAMODEL_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKTESTINGDATAMODEL_NO_DEPRECATED
#    define VTKTESTINGDATAMODEL_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: vtkTestingDataModelModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

#endif /* VTKTESTINGDATAMODEL_EXPORT_H */
